
name: Java CI with Gradle

on:
  push:
    branches: [ master ]
    paths: ".github/workflows/publish.yml"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Publish with Gradle
      run: ./publish_lib.sh
#      run: ./gradlew publishAllPublicationsToGitHubPackagesRepository
      env:
        USERNAME : "GitHub Actions"
        MAVEN_USER : "GitHub Actions"
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}



